### ISSUE TITLE
Include display names of categories and LIDIA terms and hyperlinks to LoL entries

### ISSUE THREAD

**Issue by tijmenbaarda** [CentreForDigitalHumanities/lidia-browser#13]

**Comment by ar-jan** [comment]
Plan: add the term + url combinations (LoL and/or CCR) to the Excel sheet used in lidia-zotero. When processing terms from Zotero API use the sheet from the lidia-zotero repo to add a list of term+url as JSON. Render the links (custom widget needed?).

**Comment by ar-jan** [comment]
#25.
