### ISSUE TITLE
Combine continuation annotations into main annotation

### ISSUE THREAD

**Issue by ar-jan** [CentreForDigitalHumanities/lidia-browser#4]
We need to add the `annotationText` of continuation annotations to the preceding annotation, and not create a separate entity for these annotations (or mark it as continuation and hide it, if that's simpler?).

For this we need to order all the annotations for a given attachment_id by page number and position (coordinates) on the page, looks like both are available via `data.annotationPosition`.

**Comment by tijmenbaarda** [comment]
Continuation annotations are now tied to the initial annotation in the models, but the user should not be aware of this. That can be done by adding an additional automatically populated field or property with the full annotation text.

**Comment by ar-jan** [comment]
This was completed in #14.
