### ISSUE TITLE
Make the admin interface available to anonymous users

### ISSUE THREAD

**Issue by tijmenbaarda** [CentreForDigitalHumanities/lidia-browser#8]
Simplest solution: programmatically create an account for anonymous users with reading rights, and give users who visit the site the possibility to "login" to the anonymous account, or to an account with more rights. The password editing views, etcetera, should be deactivated.

A variant to this: automatically login the user to the anonymous account when visiting the homepage, then redirect to the admin page. The user will still be able to logout and login to a real user, as long as he/she does not visit the homepage.

@ar-jan: what are your thoughts on this?

**Comment by ar-jan** [comment]
I think we should definitely aim for a solution where the user doesn't have to do anything extra. Could be logging in automatically, or maybe there's stil other ways of exposing the admin interface to anonymous users (could we re-use its features in custom views maybe?)
